version: "3.7"

x-db-variables: &db-variables
  POSTGRES_DB: blog
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin

services:

  blog:
    build: .
    environment:
      <<: *db-variables
      POSTGRES_HOST_APP: 'database'
      APP_PORT: '5000'
    working_dir: "/app"
    depends_on:
      - db
    links:
      - "db:database"
    ports:
      - "5000:5000"
    command: >
      bash -c "
      git fetch --all &&
      git reset --hard origin/master &&
      pip install -r requirements.txt &&
      python3 init_db.py &&
      python3 main.py"
  
  db:
    image: postgres
    environment: *db-variables
    ports:
      - "5432:5432"
  
  grafana:
    image: grafana/grafana:7.0.0
    restart: always
    links: 
      - "influx-db:influx"
    ports: 
      - "3000:3000"

  chronograf:
    image: chronograf:1.7-alpine
    links: 
      - "influx-db:influx"
    ports:
      - "8888:8888"
    command: chronograf --influxdb-url=http://influx:8086
    
  influx-db:
    image: influxdb:1.7-alpine
    environment: 
      - INFLUXDB_DB=db0
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    ports: 
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"